export const COMPOSER_NEW = "COMPOSER_NEW";
export const COMPOSER_CANCEL = "COMPOSER_CANCEL";
export const COMPOSER_POST = 'COMPOSER_POST';

export const FETCH_CAT_BEGIN = 'FETCH_CAT_BEGIN';
export const FETCH_CAT_SUCCESS = 'FETCH_CAT_SUCCESS';
export const FETCH_CAT_ERROR = 'FETCH_CAT_ERROR';
